name: EchoScribe
options:
  bundleIdPrefix: com.echoscribe
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  EchoScribe:
    type: application
    platform: macOS
    sources:
      - EchoScribe
    settings:
      INFOPLIST_FILE: EchoScribe/App/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.echoscribe.app
      PRODUCT_NAME: EchoScribe
      MACOSX_DEPLOYMENT_TARGET: 13.0
      SWIFT_VERSION: 5.9
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_NSMicrophoneUsageDescription: "EchoScribe needs microphone access to record audio for transcription."
      INFOPLIST_KEY_NSSystemAdministrationUsageDescription: "EchoScribe needs system administration access to record system audio."
      INFOPLIST_KEY_NSScreenCaptureUsageDescription: "EchoScribe needs screen capture access to record system audio."
      INFOPLIST_KEY_NSDocumentsFolderUsageDescription: "EchoScribe needs access to your Documents folder to save recordings and notes."
      CODE_SIGN_ENTITLEMENTS: EchoScribe/App/entitlements.mac.plist
      ENABLE_HARDENED_RUNTIME: YES
      COMBINE_HIDPI_IMAGES: YES
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: EchoScribe/App/Info.plist
      properties:
        CFBundleDisplayName: EchoScribe
        CFBundleIdentifier: com.echoscribe.app
        CFBundleName: EchoScribe
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: "13.0"
        NSMicrophoneUsageDescription: "EchoScribe needs microphone access to record audio for transcription."
        NSSystemAdministrationUsageDescription: "EchoScribe needs system administration access to record system audio."
        NSScreenCaptureUsageDescription: "EchoScribe needs screen capture access to record system audio."
        NSDocumentsFolderUsageDescription: "EchoScribe needs access to your Documents folder to save recordings and notes."
        LSApplicationCategoryType: public.app-category.productivity
        NSHighResolutionCapable: true
        NSRequiresAquaSystemAppearance: false
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
    dependencies:
      - framework: AVFoundation
      - framework: Speech
      - framework: ScreenCaptureKit
      - framework: CoreML
      - framework: CoreData
      - framework: UniformTypeIdentifiers
      - framework: AppKit
      - framework: SwiftUI
      - framework: Combine
    entitlements:
      path: EchoScribe/App/entitlements.mac.plist
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: false
        com.apple.security.device.audio-input: true
        com.apple.security.device.microphone: true
        com.apple.security.files.user-selected.read-write: true
        com.apple.security.files.downloads.read-write: true
        com.apple.security.files.documents.read-write: true
        com.apple.security.automation.apple-events: false
        com.apple.security.cs.allow-jit: false
        com.apple.security.cs.allow-unsigned-executable-memory: false
        com.apple.security.cs.disable-library-validation: false
        com.apple.security.cs.allow-dyld-environment-variables: false
